// <auto-generated />
namespace LAB6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class lab7_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lab7_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202312142106088_lab7_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
